version: '3.9'

services:
    devsu-api:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./target:/app
        networks:
            - devsu-api-net
networks:
    devsu-api-net:
        external: true